#!/usr/bin/env bash

go() {
	if [[ $arguments == "" ]]; then
		ruby-install
		exit 1
	fi

	"${HOME}/.rubies/ruby-${arguments}/bin/ruby" -v >/dev/null 2>/dev/null && already_installed="YES"
	if [[ "$already_installed" == "YES" ]]; then
		echo -e "  * ruby $arguments (${format_orange}skipped, already installed${format_reset})"
		exit 0
	fi

	dependencies

  if is_arm; then
    ruby-install ruby $arguments --no-reinstall -c -- --with-openssl-dir=$(brew --prefix openssl) CFLAGS=-DUSE_FFI_CLOSURE_ALLOC=1
  else
    ruby-install ruby $arguments --no-reinstall -- --with-openssl-dir=$(brew --prefix openssl)
  fi
}

function is_arm() {
  [[ "$(uname -m)" == "arm64" ]]
}

dependencies() {
	ruby_install_path=""
	if [[ -d "/usr/local/share/ruby-install" ]]; then
		ruby_install_path="/usr/local/share/ruby-install"
	else
		ruby_install_path="/opt/homebrew/share/ruby-install"
	fi
	which ruby-install >/dev/null || $script_dir/../bin/dani install ruby-install
	source $ruby_install_path/ruby-install.sh &&
		source $ruby_install_path/functions.sh &&
		source $ruby_install_path/functions.sh &&
		package_manager=brew ruby=ruby ruby_version="$arguments" install_deps
}

arguments="${@:2}"
format_orange='\033[0;33m'
format_reset='\033[0m'
script_dir=$( cd "$( dirname "$0" )" && pwd )
set -e
go
